### ISSUE TITLE
Example for reaching timeout error

### ISSUE THREAD

**Issue by szabgab** [tomerfiliba-org/rpyc#264]
Seeing `sync_request_timeout` I thought the client will time out after 30 sec if it does not get a response, but I could not make it trigger with this code. How can I see the timeout in action?

```
import rpyc
import sys

if len(sys.argv) < 2:
   exit("Usage {} SERVER".format(sys.argv[0]))

server = sys.argv[1]

conn = rpyc.classic.connect(server)
my_code = '''
import time
def wait_a_bit(n):
    start = time.time()
    time.sleep(n)
    end = time.time()
    return { "start" : start, "end" : end, "diff" : int(end - start) }
'''
conn.execute(my_code)

rf = conn.namespace['wait_a_bit']
print(rf(50))
```

##### Environment

client:
- Python 3.6.3.
- rpyc 3.4.4
- OSX

server
- Python 3.6.3
- rpyc 3.4.4
- Ubuntu 17.10
- running `rpyc_classic.py`

**Comment by coldfix** [comment]
Hi,

sorry for the delay. I think the timeout is not reported due to the implementation of `Connection.sync_request` which reads (as of merging #212 in 3f1cc1e):

```python
        while seq not in self._sync_replies:
            self.sync_recv_and_dispatch(timeout, True)
```

In order to time out, it should read something like this instead:

```python
        while seq not in self._sync_replies:
            if not self.sync_recv_and_dispatch(timeout, True):
                raise TimeoutError()
```

I will wait a few days before merging this (so I have some time to ponder about possible undesirable implications).

Best, Thomas
