### ISSUE TITLE
conn object is created before on_connect is finished

### ISSUE THREAD

**Issue by AndreasPantle** [tomerfiliba-org/rpyc#409]
Actually I have a strange behaviour. First I like to know if this is possible / Second maybe there is a workaround/solution for it:

I'm using rpyc for connecting to some remote embedded devices which are Busybox machines builded with Buildroot. At the embedded device I'm using the `ThreadedServer`. 

The problem is that the `def on_connect(self, conn):` method does something which requires "time". And on the other side the `c = rpyc.connect("192.168.0.99", 4711, config={"sync_request_timeout": 3000}, keepalive=True)` connection object will be created BEFORE `on_connect` is finished. Now the problem is that I get some troubles because I need to wait with the process for finishing `on_connect`.

**Comment by comrumino** [comment]
If you call `c.root` it should block until the service is ready. Reopen if that does not resolve the issue.

**Comment by AndreasPantle** [comment]
Ok thank's for your help. I'm give it a try. I don't know that this is possible at all.

**Comment by comrumino** [comment]
That was going of a shot in the dark solution. Are you able to reproduce the issue without using an embedded device? I do have a stm32f401 that I could try to reproduce it with---that would be a last resort and not ideal as it may not even reproduce the issue.

I do wonder if cgroups could be used to mimic the resource constraints of a MCU---docker does a nice job of support resource constraints. Emulating the resource constraints may be the way forward. Of course, having multiple unknowns and no steps to reproduce make debugging very time consuming. The biggest unknowns for me are if you are using a non-default configuration and if the root cause is in implementation or a core design/logic error in rpyc.

If you are able provide minimum test case to reproduce the issue, then that would be my first preference. Otherwise, I would at least need two minimalist scripts that still cause in the conn object issue in your environment. I'll reopen this issue as it is clearly not done, my bad.

Minimalist example scripts save me from the mental gymnastics required to debug this issue.

**Comment by AndreasPantle** [comment]
Maybe I missunderstood the problem - I don't know... No I build two files which are interacting in a short example to show you my problem...

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from rpyc.utils.server import ThreadedServer
import rpyc
import time
from datetime import datetime


class ControlModuleService(rpyc.Service):

    def __init__(self):
        """
        Remote Service which runs on target device.
        """

    def on_connect(self, conn):
        """
        Accept the connection from remote host.
        """

        print('%s - Hello Dave...' % datetime.now().strftime("%m/%d/%Y, %H:%M:%S"))
        time.sleep(10.0)
        print('%s - You are welcome.' % datetime.now().strftime("%m/%d/%Y, %H:%M:%S"))

    def on_disconnect(self, conn):
        """
        Disconnect the remote host.
        """

        print('%s - Bye Dave.' % datetime.now().strftime("%m/%d/%Y, %H:%M:%S"))

    def exposed_status(self):
        """
        Get the status of the target.
        """

        return '%s Here we are still alive!' % datetime.now().strftime("%m/%d/%Y, %H:%M:%S")


def main():
    try:
        # Start rpc server
        cm_server = ThreadedServer(ControlModuleService(), port=4711)
        cm_server.start()
    except Exception as e:
        print('Exception: %s' % e)


if __name__ == "__main__":
    main()
```

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import rpyc
import time
from datetime import datetime


def main():
    try:
        # Connect first
        c = rpyc.connect("127.0.0.1", 4711, config={"sync_request_timeout": 3000}, keepalive=True)
        print('%s - %s' % (datetime.now().strftime("%m/%d/%Y, %H:%M:%S"), c))
        # Here we go BEFORE the time.sleep in target.py -> def on_connect(self, conn) is ready
        print('%s - %s' % (datetime.now().strftime("%m/%d/%Y, %H:%M:%S"), c.root.exposed_status()))

        # Closing
        c.close()
    except ConnectionRefusedError:
        print('ConnectionRefusedError')
    except Exception as e:
        print(e)
    finally:
        exit()


if __name__ == "__main__":
    main()
```

Now my problem is that the c object was created BEFORE the time.sleep in the on_connect function is ready. For my understanding and if I do this in synchronisation: I have to stay in the `c = rpyc.connect("127.0.0.1", 4711, config={"sync_request_timeout": 3000}, keepalive=True)` as long as the `def on_connect(self, conn):` needs time to proceed. Is this a missunderstanding on my side?

**Comment by comrumino** [comment]
You are correct in that the point in time conn object is created is prior to on connect. For the threaded server, the server-side will allocate a Python-thread for each client. After thread allocation by `spawn(self._authenticate_and_serve_client, sock)`, service instance will call `on_connect` using the connection constructed using that client's `sock`. During `on_connect` the thread is blocked by `time.sleep` and once the thread can process `c.root.exposed_status` the time is found and returned.

It might help to show this in chronological steps and remember the server side can only process serially for each client:
1. server-side, spawn is invoked for the server and client sock
2. server-side, connection is constructed and on_connect begins execution then is blocked by the sleep
3. client-side, `datetime.now().strftime("%m/%d/%Y, %H:%M:%S")` executes **and then** `c.root.exposed_status` sends a request to the server
4. server-side, sleep no longer blocks the client's thread, `on_connect` returns, **and then** processes the `exposed_status` request **ten seconds after step 3**
5. client-side, `c.root.exposed_status` returns with a timestamp ten seconds after the previous argument executed.

Design-wise, it makes sense to me that `on_connect` will block before serving the client further. I think the part the tripped me up for a little in your example is that the print statement arguments are returned results from function calls. To me, it was easier to follow when binding the results to a name prior to use the values to formatting a string.

What is the desired behavior in your use? Is the issue that the client thinks the server is dead because the **thing that takes time** prevents the socket from responding?

**Comment by AndreasPantle** [comment]
On my target system I have to do some GPIO stuff which requires "time" until all of the IO's are set correctly. The problem here is that the connection should only be succesful if the state of the IO's is ready.
Actually I exposed a function for this which gets called after the connection is created. If the IO's are not set correctly I close the connection. So this is a workaround for the problem above. I thought it looks nicer if the connection handle is create only if the on_connect function is succed.

**Comment by comrumino** [comment]
I have fix to propose!
```
diff --git a/rpyc/utils/server.py b/rpyc/utils/server.py
index ffbfffc..b9b648c 100644
--- a/rpyc/utils/server.py
+++ b/rpyc/utils/server.py
@@ -237,6 +237,10 @@ class Server(object):
             if not self._closed:
                 self.logger.info("background auto-register thread finished")
 
+    def _pre_listen_callback(self):
+        """ performs processing routines prior to enabling the server to accept connections """
+        return True
+
     def _listen(self):
         if self.active:
             return
@@ -257,6 +261,9 @@ class Server(object):
 
     def start(self):
         """Starts the server (blocking). Use :meth:`close` to stop"""
+        if not self._pre_listen_callback():
+            self.logger.critical("Listen preprocessing callback _pre_listen_callback failed!")
+            return
         self._listen()
         self._register()
         try:

```
Moving booting delays into `_pre_listen_callback` allows you check once prior to accepting connections with  `ThreadedServer`. If there is hardware-specific preconditions for exposed methods, looking before you leap is not necessarily related to connection establishment. Does this patch work for you? Do you have any other thoughts, comments, or concerns?

**Comment by AndreasPantle** [comment]
Thank you for the patch. I did on the site-package and delete the __pycache__ folders to be aware of side effects.

No I have the version:

`version = (5, 0, 1)
version_string = ".".join(map(str, version))
release_date = "2021.01.11"
`

Actually it seems that there is no difference between the patch and the original.

Please leave this issue as no other user complains this. I like the rpyc module and I'm very thankful to have it for the communication to my embedded system. 
Maybe the solution is a blocking routine or I trie to evaluate the asynchronous operations as you suggest.
Thanks for your help!
