### ISSUE TITLE
Class integer fields interprets as strings

### ISSUE THREAD

**Issue by GregoryIstratov** [tomerfiliba-org/rpyc#414]
Hello, I'm trying to return dataclass from the exposed_create function and on the client side the returned object interprets all fields of class as strings so creating a tuple 'shape' throws exception. How should i return such objects to preserve their data types? 

##### Environment

- rpyc version: 4.1.5
- python version: 3.8
- operating system: Ubuntu 20.04

##### Minimal example

Server:

```python
@dataclass
class DataProviderInfo:
    frameWidth: int
    frameHeight: int
    zmqHost: str
    zmqPort: int

class DataProvider(rpyc.Service):
   ...

    def exposed_create(self, url):  # this is an exposed method
        ...

        self.cap = cv2.VideoCapture(url)
        w = int(self.cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        h = int(self.cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

        return DataProviderInfo(w, h, ZMQ_MANAGER_HOST, self.zmqPort)

if __name__ == "__main__":
    t = ThreadedServer(DataProvider, port=18862)
    t.start()
```

Client:

```python
con = rpyc.connect("localhost", 18862)
dp = con.root

info = dp.create("/home/greg/work/data/input.mp4")

# throws here
shape = (info.frameHeight(), info.frameWidth(), 3)
```

**Comment by comrumino** [comment]
I add the script [tests.test_test_dataclass](https://github.com/tomerfiliba-org/rpyc/commit/ee221fed06cd4e729a6edef3d6ae37970c756451) to test and it turns out that I cannot reproduce the issue. I would make sure that you either set `allow_all_attrs` to true or expose individual attributes. If that does not resolve your issue, I would make sure that there are not any bugs in your source code such ass `info.frameHeight()` which should throw `TypeError: 'int' object is not callable`.

If you can find a problem in the protocol by extending the `tests.test_dataclass`, feel free to reopen the issue.
