### ISSUE TITLE
Question: how to get ip of host inside `on_connect`

### ISSUE THREAD

**Issue by NNRepos** [tomerfiliba-org/rpyc#419]
when a new host connects, i would like to add its ip to a list.
I am aware that the `Server` object contains `self.clients`, a list of its sockets, however, i'm not sure how a `Service` can access it, via self or conn.
help would be greatly appreciated :)

**Comment by NNRepos** [comment]
if anyone is interested - i've managed to partially solve this using the following hack:
```python
class MyThreadedServer(ThreadedServer):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.service.clients = self.clients
```
the clients set contains all current socket sessions.
i would still like to know on every method call, which host called that method. that's because i want to create a list of commands done including the name of the caller.

**Comment by comrumino** [comment]
I added an example of how to do this more properly using services in `36d80aa` by using `on_connect`.

**Comment by NNRepos** [comment]
@comrumino thanks, is there a similar method to get the address from a method other than on_connect? something like:
```python
def exposed_do_thing(self):
  called_from = self.??._channel...getpeername()
  if called_from in self.sessions:
    print("yay")
```

since i'm using the same Service instance (`ThreadedServer(MyService())`) for all connections, i can't just save it as an attribute.
thank you

**Comment by comrumino** [comment]
RPyC executes `exposed_do_thing` in a frame that does not have access to the connection. Instead of using the same Service instance for all connection, you need to use a new instance for each connection and save it as an attribute. Of course, you can still share an object between connections. I added a new demo folder to show the perils of shared state when using the threaded server. The commit [c6c896d](https://github.com/tomerfiliba-org/rpyc/commit/c6c896df834653c12c17e54025402838511eb9ef) added `demos/sharing/{client.py,server.py,README.md}`.

**Comment by NNRepos** [comment]
@comrumino thanks a lot!
just to know, why don't exposed methods have access to the connection? Wouldn't it make sense to add an optional `conn`, or some `get_connection` method? It seems like that's the only thing preventing me from using a single instance rather than multiple ones.
thanks again :)
