### ISSUE TITLE
run client but get "socket.timeout:timed out",client and server are not on the same computer

### ISSUE THREAD

**Issue by yf-web** [tomerfiliba-org/rpyc#425]
```
stack trace / error log
```
**run client but get "socket.timeout:timed out"**

##### Environment

- rpyc version 4.1.5
- python version 3.7
- operating system windows10

##### Minimal example

Server ( ip is 192.168.0.123):

```python
import rpyc
from rpyc.utils.server import OneShotServer


class HelloService(rpyc.Service):
    def exposed_concat(self, remote_str):
        local_str = ' github'
        return remote_str + local_str


if __name__ == "__main__":
    server = OneShotServer(HelloService, port=12345)
    server.start()
```

Client **(on another computer)**:

```python

import rpyc


if __name__ == "__main__":
    c = rpyc.connect("192.168.0.123", 12345)
    print(c.root.concat('hello'))
```

**Comment by comrumino** [comment]
Thanks for reporting! The commit message for `de0c515` explains some context and the root cause of this issue. In short, I added `socket.getaddrinfo` to fix IPv6 support and changed the default behavior to bind to local host instead of the wildcard address. Until the next release, a workaround is to specify the hostname as `0.0.0.0`.
